### ISSUE TITLE
cannot read property "'create'"

### ISSUE THREAD

**Issue by zero16832** [sanyuered/WeChat-MiniProgram-AR-AI#1]
开发工具 报这个错误 是啥问题呐？

**Comment by sanyuered** [comment]
我用的微信开发者工具版本号1.05.2110290，调试基础库版本2.20.2。没有看到该错误。

**Comment by sanyuered** [comment]
补充：我用旧版的微信开发者工具，版本号1.03，看到了该信息。原因是开发者工具在运行代码中的wx.createVKSession()方法时，发现不存在。该错误信息不影响真机上运行AR。
