### ISSUE TITLE
模型格式支持

### ISSUE THREAD

**Issue by ycl0916** [sanyuered/WeChat-MiniProgram-AR-AI#10]
请问模型除了glb和gltf还能支持其他格式吗，gltf-loader.js 是怎么获取的，能不能拓展支持其他格式呢

**Comment by sanyuered** [comment]
1、理论上，支持three.js所有的3D格式，比如.obj、.fbx等。gltf-loader.js只支持.gltf和.glb，其他3D格式需要对应的加载器。

2、gltf-loader.js来自微信小程序官方的项目：https://github.com/wechat-miniprogram/threejs-miniprogram

3、目前，虽然小程序支持渲染3D模型，但是有几个限制。3D模型的纹理图片不能太大，否则会显示为黑色。即使不包含纹理图片的3D模型，可能也无法显示。其他3D格式的模型大小，一般都比.gltf大，可能更加无法显示。
