### ISSUE TITLE
安卓模型黑色问题

### ISSUE THREAD

**Issue by leye123456** [sanyuered/WeChat-MiniProgram-AR-AI#11]
作者你好！我这边遇到一个问题，问题出现在安卓平台，当我加载自己的gltf模型（gltf+bin+纹理）时贴图不被渲染，导致模型黑色显示，初步估计问题出现在webglBusiness.js中，劳烦作者解决一下此问题

**Comment by sanyuered** [comment]
纹理贴图变为黑色或者不显示的原因：

1、纹理图片超过了2MB

2、纹理图片宽度或高度不能超过2048像素

3、在启动AR环境（wx.createVKSession）后，像Three.Plane等基础模型的纹理图片也会变为黑色，相机画面会闪烁。
