### ISSUE TITLE
AR测距不准

### ISSUE THREAD

**Issue by BILLXZY1215** [sanyuered/WeChat-MiniProgram-AR-AI#12]
使用AR测距时，是否只支持在一个平面上？（而类似iOS自带的测距仪会主动判断在哪个平面上，从而更加精准）

在测试过程中，通过在不同角度和高度来测量同一个物体时，得到的结果是很不一样的。

**Comment by sanyuered** [comment]
1、AR可以检测多个平面，项目中圆形光标显示的位置是平面的位置。

2、AR测距有2个项目：

https://github.com/sanyuered/WeChat-MiniProgram-AR-AI
这个是本项目，测距结果是不准确的。因为该项目的AR底层平台有比较大的误差，所以计算两点之间距离不准确。

https://github.com/sanyuered/WeChat-MiniProgram-AR-AI-V2
这个是另一个项目，测距结果可以精确到厘米，和iOS测距仪的AR底层平台一样。
