### ISSUE TITLE
AR平面跟踪修改glb模型frame.camera发生异常

### ISSUE THREAD

**Issue by yuyongkun** [sanyuered/WeChat-MiniProgram-AR-AI#13]
[修改glb模型中某个mesh的map，或者对某个mesh添加map，frame.camera均会发生水平镜像，导致加载的模型定位不稳定。

如下图 ，风扇正常在右边，却显示在左边。
[https://m.silkroadcg.com/smart_ranch/model/test.jpg](url)

**Comment by sanyuered** [comment]
webglBusiness.js已升级到官方最新版的代码。
