### ISSUE TITLE
加载的glb模型如果自带贴图，模型无法显示

### ISSUE THREAD

**Issue by YaoGUanquan** [sanyuered/WeChat-MiniProgram-AR-AI#14]
`
      if (source.bufferView !== undefined) {
        sourceURI = parser.getDependency('bufferView', source.bufferView).then(function(bufferView) {
          isObjectURL = true;
          var blob = new global.Blob([bufferView], {
            type: source.mimeType
          });
          sourceURI = URL.createObjectURL(blob);
          return sourceURI
        })
      }
`

这个blob 微信小程序暂时无法使用， 请问这里可以怎么修改？

**Comment by sanyuered** [comment]
将.glb解压缩，会产生.gltf和贴图文件，然后加载.gltf即可。
