### ISSUE TITLE
请问模型一直加载不出来是哪里没设置好呢

### ISSUE THREAD

**Issue by fanedkin** [sanyuered/WeChat-MiniProgram-AR-AI#2]
![image](https://user-images.githubusercontent.com/35400121/145714961-61c8025a-71c7-44dd-834d-e46411dfc222.png)

**Comment by fanedkin** [comment]
![image](https://user-images.githubusercontent.com/35400121/145715008-8dc96de1-ee0a-476f-9ff1-88eb3de5138a.png)
显示这个报错

**Comment by LazyYangi** [comment]
不要用模拟器打开 不能显示的，另外有的个别模型无法加载  可以先试一下小程序案例里面的glb模型

**Comment by sanyuered** [comment]
> ![image](https://user-images.githubusercontent.com/35400121/145715008-8dc96de1-ee0a-476f-9ff1-88eb3de5138a.png) 显示这个报错

1、这个错误提示是因为微信开发者工具不认识新的API（wx.createVKSession()），但不影响手机真机运行AR。也可以升级微信开发者工具，这个错误提示就没有了。
2、3D模型加载不出来有2个原因：（1）小程序需要打开调试模式或设置request合法域名，才能下载远程地址的模型。（2）gltf模型有4种格式：带贴图的gltf、不带贴图的gltf，带贴图的glb、不带贴图的glb。微信小程序默认不支持带贴图的glb。
