### ISSUE TITLE
小程序真机调试的时候报错

### ISSUE THREAD

**Issue by november15** [sanyuered/WeChat-MiniProgram-AR-AI#3]
![image](https://user-images.githubusercontent.com/11310287/153383850-e1b2f07a-7819-4916-ae18-b1d91e6c7cd6.png)
麻烦帮忙看看是咋回事儿吧？
多谢

**Comment by sanyuered** [comment]
提示“OffscreenCanvas is not a constructor.”，说明小程序环境不支持OffscreenCanvas。OffscreenCanvas是离屏画布组件，需要微信小程序基础库2.16.1以上。

**Comment by november15** [comment]
好的谢谢
