### ISSUE TITLE
fetch-wechat.js" is not defined

### ISSUE THREAD

**Issue by masterflywolf** [sanyuered/WeChat-MiniProgram-AR-AI#4]
fetch-wechat.js" is not defined

**Comment by haotiansun** [comment]
same issue

**Comment by sanyuered** [comment]
> fetch-wechat.js" is not defined

原因：小程序使用了 npm包，而为了减小项目的下载大小，没有上传。在小程序编译前，要构建npm。

解决方法：微信开发者工具--菜单“工具”--构建npm，会在项目中生成miniprogram_npm文件夹，然后包含了fetch-wechat的npm包。
