### ISSUE TITLE
加载模型报错global.blob is not a constructor  是什么原因

### ISSUE THREAD

**Issue by W-ChenAMG** [sanyuered/WeChat-MiniProgram-AR-AI#5]
![image](https://user-images.githubusercontent.com/37658262/159638847-dfd952b1-6107-4fcb-bda1-7a7c83015979.png)

**Comment by W-ChenAMG** [comment]
还有一个问题，我如何双指放大或者缩小模型

**Comment by W-ChenAMG** [comment]
现在点击屏幕重新加载的时候，点个3到4次，小程序就崩了

**Comment by Dean877** [comment]
请问你解决了吗？

**Comment by sanyuered** [comment]
> ![image](https://user-images.githubusercontent.com/37658262/159638847-dfd952b1-6107-4fcb-bda1-7a7c83015979.png)

原因：提示global.blob不存在，是因为微信小程序的环境不支持blob对象。如果加载带纹理贴图的glb模型时，就会出现该错误。

解决方法：将glb转换为gltf格式的模型。另外，小程序对3D模型的渲染效果不如网页，3D模型可能显示不出来或者色彩失真。

**Comment by sanyuered** [comment]
> 还有一个问题，我如何双指放大或者缩小模型

这个要监听画布组件的手势事件，根据两个手指的距离，调整3D模型的缩放值。在源代码中，可以使用mainModel.scale.set()方法，调整模型大小。

**Comment by sanyuered** [comment]
> 现在点击屏幕重新加载的时候，点个3到4次，小程序就崩了

“用AI检测图像中的物体，将名称显示在物体上。”这个项目同时运行3D图形、增强现实、摄像头、深度学习等密集型计算，小程序会出现内存不足，然后强制退出。 小程序退出的问题来自“var decorder = wx.createVideoDecoder()”这个功能，这个功能将小程序画面录制为视频。接着从视频中截取一张图像，让AI检测是什么物体。目前找不到替换 wx.createVideoDecoder()的方法，没有解决方法。

**Comment by W-ChenAMG** [comment]
>

**Comment by W-ChenAMG** [comment]
> “用AI检测图像中的物体，将名称显示在物

不不不，我是用了ar+内容，将3d模型放置在空间中。这个应该是不会用到createVideoDecoder的，即便用那个机器人案例，也是会崩掉

**Comment by W-ChenAMG** [comment]
> ![image](https://user-images.githubusercontent.com/37658262/159638847-dfd952b1-6107-4fcb-bda1-7a7c83015979.png)
