### ISSUE TITLE
开发者工具和真机预览一直显示Loaidng 3D

### ISSUE THREAD

**Issue by Evanl-lai** [sanyuered/WeChat-MiniProgram-AR-AI#6]
![31ba1bd2980c6a605340f892a16c2d2](https://user-images.githubusercontent.com/58460652/160787229-89f48fb4-3171-4b78-aace-cc9570cf3077.png)

**Comment by sanyuered** [comment]
解决方法：请打开小程序的调试模式。

**Comment by kenchikuliu** [comment]
> 

打开了调试模式还是不行.
