### ISSUE TITLE
版本冲突

### ISSUE THREAD

**Issue by zhouzhendao123456** [sanyuered/WeChat-MiniProgram-AR-AI#7]
在npm install的时候提示
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: wechat-miniprogram-ar-ai@1.0.0
npm ERR! Found: @tensorflow/tfjs-converter@2.1.0
npm ERR! node_modules/@tensorflow/tfjs-converter
npm ERR!   @tensorflow/tfjs-converter@"2.1.0" from the root project
npm ERR!

请问如何处理呢？

**Comment by mengxin-FE** [comment]
同样遇到此问题   ![image](https://user-images.githubusercontent.com/14139852/164172355-4d95fa50-41bc-48e3-b060-0011d9433492.png)

**Comment by mengxin-FE** [comment]
使用 npm install --force才能完成安装

**Comment by sanyuered** [comment]
1、原因是package-lock.json没有包含全部npm包的版本号，当npm install时，会下载所有npm包的最新版本。@tensorflow/tfjs-converter这个第三方npm包的最新版本和它自己的依赖项冲突。
2、如果不使用package_image_classify这个项目，可以移除tensorflow相关的npm包。
3、今天上传了微信开发者工具构建的miniprogram_npm包，不需要运行npm install了。
