### ISSUE TITLE
您好，请问更换眼镜模型为面具模型后，缩放和位置应该怎么调整呢

### ISSUE THREAD

**Issue by mengxin-FE** [sanyuered/WeChat-MiniProgram-AR-AI#8]
您好，请问更换眼镜模型为面具模型后，缩放和位置应该怎么调整呢

**Comment by sanyuered** [comment]
![1-1](https://user-images.githubusercontent.com/21356275/166142691-229109ed-29f9-4bdc-81af-95152a7ff2ea.jpg)

1、找一张五官端正的人脸照片，用该项目的小程序加载或拍摄该照片，你的面具模型会叠加在照片上。然后，将你的面具模型缩放到与人脸照片匹配的大小。这个缩放大小就是模型scale属性的默认值或基准值。
2、面具模型的中心一般与人脸的中心对齐，比如鼻梁的特征点，索引值80和81。修改项目中的常量trackPointA和trackPointB的值。
